# inputDirectory  = "~/proyecto/TwoPionAnalysis/Data/Nominal/"
# outputDirectory = "/home/matias/proyecto/TwoPionAnalysis/Plots/Nominal/"
inputDirectory  = "~/proyecto/TwoPionAnalysis/Data/Nominal/"
systematicDirectory = "~/proyecto/TwoPionAnalysis/Data/Systematic/"
outputDirectory = "/home/matias/proyecto/TwoPionAnalysis/Plots/Nominal/"
# inputDirectory  = "~/proyecto/TwoPionAnalysis/Data/ME/"
# outputDirectory = "/home/matias/proyecto/TwoPionAnalysis/Plots/ME/"
